# Generated by Django 5.0.4 on 2024-05-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_payments_link_payments_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_amount",
            field=models.PositiveIntegerField(verbose_name="сумма оплаты"),
        ),
    ]
