# Generated by Django 5.0.4 on 2024-05-27 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_alter_payments_payment_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="user_followers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписчики",
            ),
        ),
    ]
